# @package _group_
logging_level: DEBUG
epochs: 5
params:
  gpus: 0
  deterministic: True
  benchmark: False
  weights_summary: null
  overfit_batches: 5
  min_epochs: ${trainer.epochs}
  max_epochs: ${trainer.epochs}
